name: creepiest
channels:
  - bioconda
dependencies:
  - python=3.5
  - numpy=1.11.*
  - scipy=0.18.*
  - scikit-learn=0.18.1
  - pandas=0.19
  - psutil=4.3.*
  - statsmodels=0.6.1
  - twobitreader=3.1.4
  - pytables=3.2.3.1
